use std::env;

pub mod pool;
pub mod replica;
pub mod server;

// Common module for all the misc operations
// TODO: move this to its respective directory structure
pub(crate) mod common {
    tonic::include_proto!("v1.common");
}

// Pool GRPC module for the autogenerated pool code
pub(crate) mod pool_grpc {
    tonic::include_proto!("v1.pool");
}

// Replica GRPC module for the autogenerated replica code
pub(crate) mod replica_grpc {
    tonic::include_proto!("v1.replica");
}

pub fn get_core_ip() -> String {
    let ipv4addr = env::var("CORE_IP").expect("CORE_IP not found");
    "https://".to_owned() + &ipv4addr + ":50051"
}
