[package]
name = "grpc"
version = "0.1.0"
edition = "2018"
authors = ["Abhinandan Purkait <abhinandan.purkait@mayadata.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.5.2"
prost = "0.8.0"
prost-types = "0.8.0"
tokio = { version = "1.12.0", features = ["full"] }
common-lib = { path = "../../common" }
dns-lookup = "1.0.8"
humantime = "2.1.0"
utils = { path = "../../utils" }

# Tracing
tracing-subscriber = "0.2.24"
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
opentelemetry-semantic-conventions = "0.8.0"
tracing = "0.1.28"

[build-dependencies]
tonic-build = "0.5.2"
prost-build = "0.8.0"
